<a href="https://colab.research.google.com/github/Nayana-G-Naik/Naik-Nayana-G-4AL17CS053/blob/master/Day3%20session%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

In [ ]:
 
import pandas as pd 
data=[2,4,6,8,10]
ds = pd.Series(data) 
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


 Write a Pandas program to convert a Panda module Series to Python list and its type

In [ ]:
 
 
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


 Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
 
 
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
 
 
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [ ]:
 
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50]

In [ ]:
 
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
['100', '200', 'python', '300.12', '400']

In [ ]:
 
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


#Write a Pandas program to sort a given Series.

In [ ]:
 
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [ ]:
 
 
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition

In [ ]:
 
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [ ]:
 
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


 
#Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [ ]:
 
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a NumPy program to generate five random numbers from the normal distribution.

In [ ]:
 
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.13919386 -0.9643996   1.84238388 -0.9117284  -0.42652821]


#Write a NumPy program to generate six random integers between 10 and 30

In [ ]:
 
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[21 15 21 11 21 16]


#Write a NumPy program to create a 3x3x3 array with random values.

In [ ]:
 
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.65648191 0.27663598 0.79561626]
  [0.82089314 0.53071494 0.5427845 ]
  [0.67567793 0.49338542 0.30219025]]

 [[0.60041924 0.40779823 0.12590251]
  [0.42128637 0.12271102 0.23948639]
  [0.62579245 0.98152996 0.01657183]]

 [[0.32401411 0.50620997 0.91862547]
  [0.936961   0.62954965 0.48129024]
  [0.05431305 0.70279106 0.3596274 ]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [ ]:
 
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.50645837 0.61347711 0.95371441 0.9502229  0.90874232]
 [0.87426912 0.73573726 0.37829697 0.39457549 0.27444282]
 [0.14349486 0.21039138 0.30897212 0.65697232 0.54071793]
 [0.77916152 0.17872625 0.95471396 0.54776435 0.01034909]
 [0.72127604 0.91784454 0.85146124 0.9161484  0.64892704]]
Minimum and Maximum Values:
0.010349088394796757 0.9547139571810557


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [ ]:
 
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.16099657 0.4999255  0.52304822 0.84885882]
 [0.41218269 0.55547126 0.98510118 0.29186866]
 [0.92520417 0.65722098 0.3000574  0.53799162]
 [0.96427926 0.09924026 0.19204372 0.71545515]
 [0.93957001 0.23246356 0.54193897 0.47768468]
 [0.01128687 0.66467855 0.28044244 0.958357  ]
 [0.12181657 0.78017958 0.92345648 0.24117605]
 [0.60626649 0.45241651 0.70793582 0.17678443]
 [0.84206099 0.00530797 0.3788765  0.95291639]
 [0.29140292 0.8344397  0.00837741 0.91054217]]
First 5 rows of the above array:
[[0.16099657 0.4999255  0.52304822 0.84885882]
 [0.41218269 0.55547126 0.98510118 0.29186866]
 [0.92520417 0.65722098 0.3000574  0.53799162]
 [0.96427926 0.09924026 0.19204372 0.71545515]
 [0.93957001 0.23246356 0.54193897 0.47768468]]
First 3 columns of the above array:
[[0.16099657 0.4999255  0.52304822 0.84885882]
 [0.41218269 0.55547126 0.98510118 0.29186866]
 [0.92520417 0.65722098 0.3000574  0.53799162]
 [0.96427926 0.09924026 0.19204372 0.71545515]
 [0.93957001 0.2324

 
#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [ ]:
 
 
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[5 3 2 6 0 8 9 1 4 7]
Same result using permutation():
[9 8 7 2 6 4 1 0 3 5]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
 
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[7 2 4 6 9 8 5 0 3 1]
[0 1 2 3 4 5 6 7 8 9]
